### ISSUE TITLE
Discussion - Survey Data Collection and Respondent Identification

### ISSUE THREAD

**Issue by edgrosvenor** [artisan-build/survey-engine#1]
### Background

One of the core pillars of my business is going to be data collection and analysis, often by way of surveys. I want the people who take my surveys to feel confident about answering honestly even if the question is sensitive or controversial. So I want to be able to demonstrate that their data is truly anonymous. However, I also want to be able to enforce a "one person, one vote" paradigm. So I need to not know how you answered the questions, but I need to know that you answered the questions. 

### Solving The Problem

Fundamentally the only solution I have to far is that this particular problem will be solved here in this open source repo. I can think of ways to solve it but I want to know that the solution I come up with has passed the smell test with people I trust. People like you.

The broad strokes of my current thinking are that I'll store all survey data in a single table that looks like thing like this:

```
$table->id();
$table->unsignedBigInteger('survey_id'); // I will be running multiple surveys simultaneously covering lots of topics
$table->json('responses'); // Just the key / value pairs of the responses, no respondent data at all
$table->timestamps();
```

Surveys are pretty simple. They are just big flat arrays of key / value pairs. When it's time to do the analysis of the data, I'll dump them to a csv and send them to my number crunchers to work their Excel magic. So just storing all the responses for all the different surveys as an array it perfectly fine. I won't be running any queries against this stuff on the web at all.

Then I'll have some sort of a receipts table that just records that a user took a particular survey:

```
$table->id();
$table->unsignedBigInteger('survey_id');
$table->string('email');
```

So I know a person with the email address took the survey but I don't actually connect the survey response record to the receipt record in any way. Easy enough.

The challenge is how do I make it so that I can't just use the order in which the records appear in each table to match one with the other?

### What this repo will contain

This will end up being a Laravel app (because it's what I know best) that provides an API that will store all my survey results and make sure that each email address can only take a given survey once. My primary motivation for making it open source is to give my respondents confidence in the anonymity of their responses but if I can also make this a useful product for others to use I'd be all for it.

### What I Need From You

Tell me all the ways I'm going to screw this up so I can avoid them.

**Comment by edgrosvenor** [comment]
I guess the really obvious answer is to just store a hash of the respondent's email address and not the address itself. Is that enough?

**Comment by iAmKevinMcKee** [comment]
Hash of the email is definitely secure. You could change the ids to uuids so there no indication of which came first.

**Comment by edgrosvenor** [comment]
@iAmKevinMcKee Thanks. What sent me down a rabbit hole is some of the tactics I'm going to be using to incentivize completion of certain surveys (giveaways, etc.). But I can definitely make all those work without actually storing the respondent's email address myself.

I like the uuid suggestion and I'll employ it just to add that additional layer of obfuscation.
